services:
  whisper-server-##:
    image: ghcr.io/jemeyer/whisper-server:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['##']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      whisp-net:
        aliases:
          - whisper-server-##

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      NGINX_CONF: |
        events { }
        http {
            upstream whisper_backend {
                server whisper-server-##:8000;
            }
            server {
                listen 80;
                location / {
                    proxy_pass http://whisper_backend;
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $$http_upgrade;
                    proxy_set_header Connection upgrade;
                    proxy_set_header Host $$host;
                }
            }
        }
    entrypoint: echo "$NGINX_CONF" > /tmp/nginx.conf && exec nginx -c /tmp/nginx.conf -g "daemon off;"'
    depends_on:
      - whisper-server-##
    networks:
      - whisp-net

networks:
  whisp-net:
    driver: bridge
